[tools]
bat = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
helm = "latest"
jq = "latest"
kubectl = "1.36"
kustomize = "latest"
rclone = "latest"
ripgrep = "latest"
shellcheck = "latest"
sops = "latest"
yq = "latest"
