[tools]
actionlint = "latest"
apko = "latest"
bat = "latest"
bazelisk = "latest"
cosign = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
gh = "latest"
helm = "latest"
jq = "latest"
kubectl = "1.36"
kustomize = "latest"
lazygit = "latest"
melange = "latest"
rclone = "latest"
ripgrep = "latest"
shellcheck = "latest"
sops = "latest"
uv = "latest"
yq = "latest"
zizmor = "latest"
zoxide = "latest"
